### ISSUE TITLE
Bring back xmmv

### ISSUE THREAD

**Issue by ralsei** [wmutils/opt#11]
sxhkd no longer supports the feature that replaced xmmv, so it's needed again.

It'd also be nice if you could resize windows w/ xmmv, albeit that might be asking too much.

**Comment by greduan** [comment]
What was that feature? Just curious.

**Comment by lwilletts** [comment]
It's a C program that allows moving of a window with the mouse. I've created #12 to add the latest version (known to me) written by dcat back into opt.

**Comment by greduan** [comment]
Ah I see. Cool

**Comment by z3bra** [comment]
Fixed as per commit a84e338.
