### ISSUE TITLE
resize window

### ISSUE THREAD

**Issue by derrickcope** [wmutils/opt#17]
how do you configure the xmmv resize window function in sxhkd? Thanks

**Comment by z3bra** [comment]
The exact same way you configure your other applications in sxhkd: by binding it to a key.

**Comment by derrickcope** [comment]
sorry if my question is dumb. 

```
alt + shift + w
xmmv $(pffw)
```

is how i have it configured to move the window.
How would I change this to resize instead? is there a switch?
Thank you

**Comment by lwilletts** [comment]
```
mod1 + !button3
wrs -a %i %i $(pfw)
```

**Comment by derrickcope** [comment]
thank you for that answer but 

```
wmv -a %i %i 
wrs -a %i %i
```

 were deprecated by sxhkd. I saw there was a recent commit that added to xmmv in opt. Does this work yet? I love using wmutils but it would be great if the mouse functions worked a little. I have been usisg it with tinywm to get a little more mouse functionality but would like to go back to straight wmutils. Is wrs -a%i %i working for you?

**Comment by lwilletts** [comment]
Personally, I have not tried because I haven't used Linux on the Desktop in about 2-3 months. I believe there might be a way to get sxhkd to do what my command did, but in a different manner - unfortunately I don't have the time to troubleshoot this. You could also raise an issue over on sxhkd and see if baskerbae has a similar solution using his new commits to sxhkd.

**Comment by z3bra** [comment]
Derrick Cope wrote:

> thank you for that answer but 
> 
> ```
> wmv -a %i %i 
> wrs -a %i %i
> ```
> 
>  were deprecated by sxhkd.

When the upstream version of a software breaks the API, you're left with 3
choices:
1. keep the old version of the software. For now, I still use version 0.5.5 and
   it works great.
2. adapt to the API change. sxhkd now writes pointer coordinates to a socket,
   and you can change the format written to this socket. This change happenned
   for a reason, and it's probably easy to write a script to do that.
3. Change the way you do that, and be creative. By being so modular, `wmutils`
   provides you with multiple ways to do what you might try to achieve. For
   example:
   
   alt + @button3
       wrs -a $(wmp) $(pfw)

> I saw there was a recent commit that added to xmmv in opt. Does this work yet? I love using wmutils but it would be great if the mouse functions worked a little. I have been usisg it with tinywm to get a little more mouse functionality but would like to go back to straight wmutils. Is wrs -a%i %i working for you?

`xmmv`, as the name suggest, moves windows. It would be easy to write a `xmrs`
command to resize windows. As of today, there are mutliple ways to handle mouse
focus with wmutils, and a good one is to use an application like swm[0] for
that. Tinywm might be a good option too, though I don't know to which extents it
works with wmutils.

[0] https://github.com/dcat/swm
