### ISSUE TITLE
respond to fullscreen request?

### ISSUE THREAD

**Issue by aeosynth** [wmutils/opt#25]
how do apps manage their fullscreen state? for instance `sxiv -fr .` does not start in fullscreen. `wew` doesn't appear to listen to fullscreen requests. do you fullscreen the app twice, through the app's interface, as well as with `wmutils`?

**Comment by z3bra** [comment]
`wmutils` idea is that YOU control your apps, not them. If you want an app to go fullscreen, you can do so with `wtp $(wattr xywh $(lsw -r)) $WID)`. `wew` is thus not supposed to listen to "requests". Such EWMH specific behavior are simply ignored by the tools.
