### ISSUE TITLE
chwb2 not working as expected

### ISSUE THREAD

**Issue by kush4gra** [wmutils/opt#45]
I was trying to use the script written by https://github.com/neeasade/dotfiles/blob/master/wm/.wm/scripts/visual/2bspwm  provided by @neeasade which uses chwb2 to draw on borders
which didn't work, nor it was giving out any output.
On finding out the problem, I realise that chbw2 is not working as it was exepected ( I use bspwm )
It was not giving out any output or visual change.
Later on , I tried chwb to draw border so that another border may be drawn using chwb2 over it, 
But on bspwm, all chwb is doing is changing the border color temporaly until I refocus the mouse on that window, whereas if I use the -size arguement , then the window seems to shift a bit toward left corner without any change in border size
Can you please help me figuring this out....
Thanks in advance

**Comment by neeasade** [comment]
Hi, if you are using that script, you might try uncommenting the commented out default colors there (above the theme get, I also just pushed an edit). You can test that chwb2 is working (it is for me in bspwm) EG like so: 

``` sh
bspc config border_width 10
chwb2 -I '000000' -O 'cccccc' -i 5 -o 5 $(bspc query -N -n)
```

edit: note your bspwm border width has to be large enough for what you're trying to draw in with chwb/chwb2. also, if you are interested in n borders, rather than 1 or 2, you might try out chwbn from https://github.com/neeasade/opt

**Comment by kush4gra** [comment]
> note your bspwm border width has to be large enough for what you're trying to draw in with chwb/chwb2 


I know that from a previous issue, I read before from 
and `chwb2 -I '000000' -O 'cccccc' -i 5 -o 5 $(bspc query -N -n)` or any chwb2 command has no effect whatsoever

I cant figure out the slightest of what the problem is.
Is the script still working on your system?

**Comment by neeasade** [comment]
> Is the script still working on your system?

yes: https://0x0.st/iasy.png

**Comment by kush4gra** [comment]
Can you think what can be causing it, it is same in both i3 and bspwm.. 
Might have a bit to do with display manager or something else...?

**Comment by kush4gra** [comment]
Except for the chwb2 part, rest of the  script is working as expected. If I replace that line with  `chwb -c 00ff00 $(pfw) ` then all borders are turning green as expected
But I can't figure out the problem with chbw2.
It is throwing an error if combined border size exceeds current size as expected, but otherwise no effect.
Can you please help. cant really figure it out

**Comment by kush4gra** [comment]
Nevermind, reinstalling the xcb libraries did the trick...no idea why it was
