### ISSUE TITLE
How to build on FreeBSD

### ISSUE THREAD

**Issue by plasmoduck** [wmutils/opt#49]
How can I build on FreeBSD? I have all the xcb libs installed but can't find them

**Comment by z3bra** [comment]
You might need to edit `config.mk` to include the path to your xcb libs.

**Comment by plasmoduck** [comment]
How so exactly? I changed PREFIX to = /usr/local/
what else?

✗ doas make install       
CC util.c
util.c:3:10: fatal error: 'xcb/xcb.h' file not found
#include <xcb/xcb.h>
         ^~~~~~~~~~~
1 error generated.
*** Error code 1

**Comment by plasmoduck** [comment]
Perhaps you can make a diff?
