### ISSUE TITLE
You're not supposed to understand this issue.

### ISSUE THREAD

**Issue by demurky** [wmutils/opt#51]
Just a reminder that this bit of the code is ridiculous and needs fixing/explanation.

https://github.com/wmutils/opt/blob/140f4677e614c6fdc130103dfc1c8ec970043e4f/chwb2.c#L72-L79

**Comment by z3bra** [comment]
This is a tribute to someone.

And btw, calling people "ridiculous" when you don't understand something isn't appropriate and won't make people inclined to "fix" your issue.
