### ISSUE TITLE
wew doesn't catch event 4 (button press) or 5 (button release).

### ISSUE THREAD

**Issue by lwilletts** [wmutils/opt#6]
Due to the glitch that people are experiencing in the other open issue surrounding wew event 7, I thought I would try and and focus my windows by using a button press. However, wew produces no output at all to my shell when I press any button on my mouse. Any ideas?

**Comment by z3bra** [comment]
Enable event `XCB_EVENT_MASK_BUTTON_PRESS` in `wew.c`.
